version: '3'
services:
  api:
    build: ./app/
    volumes:
      - ./app/:/app
    command: uvicorn api.fastapi.api_entrypoint:fast_api_app --host 0.0.0.0
    env_file:
      - ./variables/dev.example.env
    ports:
    - "8000:8000"
  grpc:
    build: ./app/
    volumes:
      - ./app/:/app
    command: python grpc_entrypoint.py
    env_file:
      - ./variables/dev.example.env
    ports:
      - "5555:5555"
  celery_worker:
    build: ./app/
    volumes:
      - ./app/:/app
    command: celery -A task_runners.celery.worker_entrypoint  worker --loglevel=info
    env_file:
      - ./variables/dev.example.env
  redis:
    image: "redis:alpine"