version: '3'
services:
  celery_worker:
    build: ./app/
    volumes:
      - ./app/:/app
    command: celery -A task_runners.celery.worker_entrypoint  worker --loglevel=info
    env_file:
      - ./variables/dev.example.env
  redis:
    image: "redis:alpine"