# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import interface_pb2 as interface__pb2


class InterfaceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
            "/interface.Interface/Add",
            request_serializer=interface__pb2.AddRequest.SerializeToString,
            response_deserializer=interface__pb2.AddResponse.FromString,
        )


class InterfaceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_InterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Add": grpc.unary_unary_rpc_method_handler(
            servicer.Add,
            request_deserializer=interface__pb2.AddRequest.FromString,
            response_serializer=interface__pb2.AddResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("interface.Interface", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Interface(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Add(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/interface.Interface/Add",
            interface__pb2.AddRequest.SerializeToString,
            interface__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
